### ISSUE TITLE
Bails out improperly when facing a trailing exponential, instead of falling back on fixed floating-point

### ISSUE THREAD

**Issue by zhihaoy** [lemire/fast_float#19]
Here is a screenshot of gdb session

![image](https://user-images.githubusercontent.com/43971430/98290043-ad57ad00-1f6e-11eb-9930-c1935329b8d1.png)

You can find that when the floating-point fails to parse, it tries to parse nan/inf.  And at the time it fails again, it forgot to set `answer.ptr` to anything meaningful.

Expected result:

`ptr` points to `'e'`.

**Comment by lemire** [comment]
Thank you for your report. Much appreciated.

>  it forgot to set answer.ptr to anything meaningful.

I agree with you that it is a bug in the library in the sense that I misinterpreted the C++ standard (I think). It is possible that we disagree as to what is happening.

What it does it to set "ec = invalid_argument", so it flags the string as an invalid number because it considers (rightly so) that 3.14e is invalid. Now, it should, when it fails to detect a number, return an an error *and* set the pointer to the first character. It fails to do the latter... 

However, in this case, you are correct, it should set ptr to 'e' *but* that's because it should not return an error, instead, it should stop parsing when it encounters the 'e' and figures out that it cannot be part of an exponential.

I will be issuing a patch that will be part of the next release.

Thanks again.

**Comment by lemire** [comment]
I have reworded the issue.
